bsd-user: space required after semicolon
This patch fixes error style problems found by checkpatch.pl:
ERROR: space required after that ','

Signed-off-by: Liyang Shi <shiliyang@huawei.com>